### ISSUE TITLE
Review our use of `impl Stream` in e.g. Match queries

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-driver-rust#21]
Currently our Match queries return `impl Stream<Item = ConceptMap>`.

This becomes a particular problem in the Concept API. We want to define methods such as `get_instances` in a trait, but trait methods cannot return `impl Stream`.

It _might_ be more useful to users if they knew the exact type of Stream. Trouble is, that type is a super-complex type.

We should investigate the performance impact of using `BoxStream`. If not, we may need to not define these methods in traits. It may be worth consulting the Rust API guidelines.

**Comment by flyingsilverfin** [comment]
This is expected and we no longer use this API
