### ISSUE TITLE
Check if we need `TypeDBStub.ensureConnected` from Client Java

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-driver-rust#23]
gRPC Java has connection failure recovery logic that somewhat flies in the face of what we need - an exponential backoff algorithm before it automatically reconnects.

This has proven to be an issue in Client Java, where after killing a Cluster node, we might have to wait quite a long time before it's able to reconnect to a new node.

We should check if `tonic` uses similar logic, and if so, ensure we handle the scenario correctly.

**Comment by flyingsilverfin** [comment]
Tonic implements this for us, so we can close this issue
