### ISSUE TITLE
Debug formatting Client errors should include the error message shown when display formatted

### ISSUE THREAD

**Issue by nikolaimerritt** [vaticle/typedb-driver-rust#44]
## Problem to Solve
An error message is given when a TypeDB Client error is display formatted. This error message is not produced when debug formatting the same error message. This is unintuitive, as debug printing an object should yield at least as much diagnostic information as display printing the object.

## Current Workaround
We both debug format TypeDB Client errors to show the kind of error, and display format the errors to show their error message. 

## Proposed Solution
TypeDB Client errors show their enum instance and error message when debug formatted.

**Comment by flyingsilverfin** [comment]
Done in #286
